# Generated by Django 4.2 on 2023-04-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField()),
                ('primary_skills', models.TextField(null=True)),
                ('secondary_skill', models.TextField(null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField()),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
