# Generated by Django 4.2 on 2023-04-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='returned_count',
            field=models.IntegerField(default=0),
        ),
    ]
