# Generated by Django 4.2 on 2023-04-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_provider_returned_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='secondary_skill',
            new_name='secondary_skills',
        ),
    ]
