# Generated by Django 4.2 on 2023-04-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_secondary_skill_provider_secondary_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='secondary_skills',
            new_name='secondary_skill',
        ),
    ]
